version: 0.1

proxy:
  remoteurl: https://registry-1.docker.io
log:
  level: debug  # Keep debug during initial testing
http:
  addr: 0.0.0.0:5000
cache:
  blobdescriptor: inmemory
storage:
  filesystem:
    rootdirectory: /var/lib/registry