version: 0.1

storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true    # Allows you to delete images

http:
  addr: 0.0.0.0:5000
  headers:
    X-Content-Type-Options: [nosniff]

log:
  level: info       # Changed from debug to info for production
  formatter: text
  fields:
    service: registry

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3