name: docker-registry

services:
  server:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./storage:/var/lib/registry