name: docker-registry

services:
  server:
    image: registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./storage:/var/lib/registry